Traceback (most recent call last):
  File "forward.py", line 69, in <module>
    getInput()
  File "forward.py", line 16, in getInput
    with open(arg[2]) as f:
IOError: [Errno 2] No such file or directory: '/Users/sparshagarwal/OneDrive/Fall'
