Traceback (most recent call last):
  File "euler_assemble.py", line 5, in <module>
    with open(arg[1]) as f:
IOError: [Errno 2] No such file or directory: '/Users/sparshagarwal/OneDrive/Fall'
